# -*- coding: utf-8 -*-
"""Day2-HW.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QWd9s-yLbBw8AapzXBtxf_TCofrd0cbn

Question 1 - Create list and swap the second half of list with first half of the list and print it on screen.                                            
Solution : I will create a list with 10 elements by using range function. I will add a new temporary variable for swapping and will use for loop to swap values of list.
"""

numberslist = list(range(10))
#print the list before swapping
print("List before swapping :", numberslist)

temp    = numberslist[0]
listlen = len(numberslist)
for i in range(int(listlen/2)):
  temp    = numberslist[i]
  numberslist[i]= numberslist[int(listlen/2)+ i]
  numberslist[int(listlen/2)+ i] = temp
  
#print the list after swapping
print("List after swapping :", numberslist)

"""Question 2 : Ask the user for the input a single digit integar number to a variable n. Print out all even numbers from 0 to n (including n).                  
Solution : Create a variable with number n and ask user input for a integar value. then use for loop along with mod condition in it.

"""

n = int(input("Please enter a single digit integar : "))

if n < 10:
  for i in range(n+1):
    if i % 2 == 0:
      print(i)
else:
  print("Please enter only single digit number")