# -*- coding: utf-8 -*-
"""Day3-HW.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bNe5vVhKEiwmiqAmWWMv7NBPlvfjPFFx

Q1 - User login application
- Get User name and password as input from user
- Check value in if statement and tell the user if they were successful
"""

print("Welcome to the login application")

usertemp     = "MahaJamali"
passwordtemp = "test@maha123"

username = input("Please enter user name :")
password = input("Please enter password : ")

if (username != usertemp and password != passwordtemp):
  print("Username and password are incorrect")
elif (username != usertemp and password == passwordtemp):
  print("Username is not valid")
elif (username == usertemp and password != passwordtemp):
  print("Password is incorrect")
else:
  print("Hurray you have logged in successfully!")

"""Q2 - Try to build same user login application but this time user dictionary

"""

print("Welcome to the login application")

loginIds = {"MahaJamali":"test@maha123", "Arsalan": "id"}

username = input("Please enter user name :")
password = input("Please enter password : ")

if (username in loginIds.keys() and password == loginIds.get(username)):
  print("Hurray you have logged in successfully!")
elif (username not in loginIds.keys() and password in loginIds.values()):
  print("Username is not valid")
elif (username in loginIds.keys() and password != loginIds.get(username)):
  print("Password is incorrect")
else:
  print("User and password are incorrect")