# -*- coding: utf-8 -*-
"""Day4-HW.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13Pf_wF5gjgCq0xQJVP62zFvl51kTaFoE

Question : Find prime number between 0 to 100 using functions
"""

#Check the prime number by using mod method
def CheckPrimeNumber(num):

  for i in range (2, num):
    if num % i == 0:
      return False

#Print the Prime numbers
def PrintPrimeNumbers():

  print("Printing prime numbers from 0 to 100") 

  j = 2
  while j <= 100:
    IsPrimenumber = CheckPrimeNumber(j) 
    j = j+1;
    if IsPrimenumber != False:
      print(j -1)
 
#Calling the print prime number function
PrintPrimeNumbers()