# -*- coding: utf-8 -*-
"""Day5-HW.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12wkm_wpipyt1sERpEES1kgRTxIF-tQFn

Question : Create three classes named Animals, Dogs and Cats. Add some features to these classes. Create some functions with these attributes. Use the inheritance.
"""

class Animals():

  def __init__(self, name, gender, age, sound):
    self.PetName       = name
    self.PetGender     = gender
    self.PetAge        = age
    self.PetSound      = sound

  def printName(self):
    print("My name is :", self.PetName)

  def displayGender(self):
    print("Gender :",self.PetGender)

  def showAge(self):
      print("Age is : ", self.PetAge)

  def sound(self):
    print("Sound is : ", self.PetSound)

class Dogs(Animals):
  pass

  DogKids = "Pup"

  def __init__(self, name, gender, age, sound):
    super().__init__(name, gender,age, sound)

  def displayDogKidsName(self):
      print("The baby of Dog is called ", self.DogKids)

class Cats(Animals):
  pass

  CatKids = 'Kitten'
 
  def __init__(self, name, gender, age, sound):
    super().__init__(name, gender,age, sound)
  
  def displayCatKidsName(self):
      print("The baby of Cat is called as ", self.CatKids)

print("Welcome to Dogs information area")
new_Dog = Dogs("Lofy", "Male", 3, "Brake")
dir(new_Dog)

new_Dog.printName()
new_Dog.displayGender()
new_Dog.showAge()
new_Dog.sound()
new_Dog.displayDogKidsName()

new_Dog1 = Dogs("Melody", "Female", 5, "Brake")
dir(new_Dog1)

new_Dog1.printName()
new_Dog1.displayGender()
new_Dog1.showAge()
new_Dog1.sound()
new_Dog1.displayDogKidsName()

print("Welcome to Cats information area")
new_Cat = Cats("Lorean", "Male", 4, "Meow")
dir(new_Cat)

new_Cat.printName()
new_Cat.displayGender()
new_Cat.showAge()
new_Cat.sound()
new_Cat.displayCatKidsName()

new_Cat1 = Cats("Tom", "Male", 7, "Meow")
dir(new_Cat1)

new_Cat1.printName()
new_Cat1.displayGender()
new_Cat1.showAge()
new_Cat1.sound()
new_Cat1.displayCatKidsName()